### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by travankor** [orhun/k3rmit#10]
Can you add a way to customize theme options? Something so that [base-16](https://github.com/chriskempson/base16) works? [Example](https://github.com/khamer/base16-termite/blob/master/themes/base16-ashes.config) of how the format can look.

**Comment by orhun** [comment]
So, are you suggesting to update the k3rmit config format according to the base-16?

**Comment by travankor** [comment]
Actually, I missed the existing themeing colours. But can you add 256 color support (`tput colors` says 256)?

**Comment by orhun** [comment]
Can you give an example about the color scheme you want to use?

**Comment by travankor** [comment]
I tried to add 
```
# extended base16 colors
color16 0xfe8019
color17 0xd65d0e
color18 0x3c3836
color19 0x504945
color20 0xbdae93
color21 0xebdbb2  
```
but I get `fish: 'k3rmit' terminated by signal SIGSEGV (Address boundary error)`

**Comment by orhun** [comment]
okay I see, it's a bug due to the fixed size of [termPalette](https://github.com/orhun/k3rmit/blob/master/src/k3rmit.c#L72) variable. I'll check if GDK supports extended colors and keep this issue updated.

**Comment by orhun** [comment]
unfortunately, [vte_terminal_set_colors](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-colors) function does not support extended colors.

```
(k3rmit.o): VTE-CRITICAL **: 13:10:33.614: void vte_terminal_set_colors(VteTerminal*, const GdkRGBA*, const GdkRGBA*, const GdkRGBA*, gsize): assertion '(palette_size == 0) || (palette_size == 8) || (palette_size == 16) || (palette_size == 232) || (palette_size == 256)' failed
```
I'll keep looking for alternatives.

**Comment by travankor** [comment]
What [termite](https://github.com/thestinger/termite/blob/master/termite.cc#L1371) does if this helps

**Comment by orhun** [comment]
I've changed the config file format and updated the palette size to 256. Can you try the extended colors now?

**Comment by orhun** [comment]
https://github.com/orhun/base16-k3rmit

**Comment by travankor** [comment]
Thanks! It's works now.
