### ISSUE TITLE
Let Control+W pass through

### ISSUE THREAD

**Issue by mawww** [orhun/k3rmit#6]
Hello,

Currently k3rmit interprets Control+W as a tab closing command. This is a pretty common readline binding (that deletes the word before the cursor), so I would suggest to switch that to something else.

In general, I think it would be good to avoid binding anything to Control+Letter as those are frequently used by terminal applications.

**Comment by orhun** [comment]
Hey,
Thanks for reporting this issue. I'll fix this when I got time to work on k3rmit. Do you have any suggestions for  these key bindings other than Ctrl + <key> ?

**Comment by mawww** [comment]
Hello,

I dont rely on tabs at all, so I do not care that much where the binding ends up, but I'd suggest at least to move it to Control+Mod1+W as there is already other commands using those modifiers and it is less likely to conflict with terminal applications.

**Comment by orhun** [comment]
I've changed the Ctrl + key bindings to Ctrl + action_key + key with 05744c07e7fddd49fdff768d9b0fd61fba8843b7
Can you build from source and test if it works for your configuration?

**Comment by mawww** [comment]
Seems to work fine, thanks !
