### ISSUE TITLE
Title option crashes terminal

### ISSUE THREAD

**Issue by XeGrox** [orhun/k3rmit#7]
Launching a terminal with `k3rmit --title ...` causes the terminal to open then close immediately although this option doesn't seem to be implemented yet

**Comment by orhun** [comment]
getopt parses `--title` option as `-e` since the argument is not implemented and contains 'e'.
```
-e, command to execute in terminal
```
Eventually, it tries to execute `...`  and exits after that. So the only thing that I can do about this issue is implementing `--title` argument which I'm not sure if it's necessary.

**Comment by XeGrox** [comment]
#8
